#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import os

res_dir = "./result"
data = ""
temp = [f for f in os.listdir("./data") if f.endswith('.txt')]

for item in temp:
    title = item.split('.')[0][7:]
    with open("./data/" + item, 'r', encoding='ansi') as f:
        data = f.read()
    os.makedirs(f"{res_dir}/{title}")
    with open(f"{res_dir}/{title}/{item}", "w", encoding="utf-8") as fl:
        fl.write(data)


