#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
def print_func_name(func):
    # 包装新旧功能
    def wrapper(*args, **kwargs):
        # 增加的新功能
        print('decorator')
        print(func.__name__)
        # 旧功能
        func(*args, **kwargs)

    return wrapper


@print_func_name
def say_hello():
    print_func_name(say_hello)
    print('hello')


@print_func_name
def say_bye():
    print_func_name(say_bye)
    print('bye')


if __name__ == '__main__':
    say_hello()
    # say_bye()
