#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
class Enemy:
    def __init__(self, name: str, atk: int, speed: int = 0, hp: int = 0) -> None:
        """

        :rtype: None
        :param name: 名字
        :param atk: 攻击
        :param speed: 速度
        :param hp: 生命值
        """
        self.name = name
        self.atk = atk
        self.atk_speed = speed
        self.hp = hp

    @property
    def name(self):
        return self.__name

    @name.setter
    def name(self, values):
        self.__name = values

    @property
    def atk(self):
        return self.__atk

    @atk.setter
    def atk(self, value):
        self.__atk = value

    @property
    def atk_speed(self):
        return self.__speed

    @atk_speed.setter
    def atk_speed(self, value):
        if 0 <= value <= 10:
            self.__speed = value
        else:
            self.__speed = 0
            raise AttributeError('错误')

    @property
    def hp(self):
        return self.__hp

    @hp.setter
    def hp(self, value):
        if 0 <= value <= 100:
            self.__hp = value
        else:
            self.__hp = 0
            raise AttributeError('错误')


if __name__ == '__main__':
    test = Enemy('zx', 200, 10, 100)
    print(test.name)
    # print(test.name(), test.hp(), test.atk_speed(), test.atk())
