#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
class Apple:
    def func1(self):
        pass


# 泛化
class A1(Apple):
    pass


A1().func1()


# 关联
class A2:
    def __init__(self):
        """将类作为自身数据"""
        self.apple = Apple()


A2().apple.func1()


# 依赖
class A3:
    def apple(self, value):
        """将类作为方法的参数传入"""
        value.func1()


A3().apple(Apple)
