#  Copyright (c) 2022. Generated by Gu.

import random

n = 50
counts = 10000  # 实验次数
counter = 0  # 统计出现重复生日的次数
birthdays = []
for i in range(counts):
    for j in range(n):
        birthdays.append(random.randint(1, 365))
    if len(birthdays) > len(set(birthdays)):
        counter = counter + 1
    birthdays = []
print(n, "个人中至少有两个人生日相同的概率:{:.2%}".format(counter / counts))
