#  Copyright (c) 2022. Generated by Gu.
# -*- coding:utf8 -*-
class Student:
    def __init__(self, n, a, s):
        self.name = n
        self.age = a
        self.score = s


def input_student():
    ls = []
    while True:
        n = input("请输入姓名：")
        if not n:
            break
        a = int(input("请输入年龄："))
        s = int(input("请输入成绩："))
        stu = Student(n, a, s)
        ls.append(stu)
    return ls


def output_student(lst):
    for stu in lst:
        print("姓名", stu.name,
              "年龄", stu.age,
              "成绩", stu.score)


def main():
    ls = input_student()
    output_student(ls)


if __name__ == '__main__':
    main()
