#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
class QueueError(Exception):
    pass


class Node:
    def __init__(self, value, next=None):
        self.value = value
        self.next = next


class Lqueue:
    def __init__(self):
        self.front = self.rear = Node(None)

    def is_empty(self):
        return self.front == self.rear

    def enqueue(self, value):
        self.rear.next = Node(value)
        self.rear = self.rear.next

    def dequeue(self):
        assert not self.is_empty(), QueueError('Queue is empty')
        self.front = self.front.next
        return self.front.value

    def display(self):
        while not self.is_empty():
            print(self.dequeue(), end=' ')

    def clear(self):
        self.front = self.rear


if __name__ == '__main__':
    sq = Lqueue()
    sq.enqueue(10)
    sq.enqueue(30)
    sq.enqueue(50)
    print(sq.dequeue())
    sq.display()
