#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
ls = [1, 2, 3, 4, 6, 7, 8, 9]


def search(lst, key):
    """二分查找, 数列必须有序"""
    low = 0
    high = len(lst) - 1
    while low <= high:
        mid = (low + high) // 2
        if lst[mid] < key:
            low = mid + 1
        elif lst[mid] > key:
            high = mid - 1
        else:
            return mid
    return


print('key index is:', search(ls, 6))
