#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
"""创建二级子进程防止僵尸进程"""
import os
import time


def f1():
    for i in range(4):
        time.sleep(4)
        print('写代码...', i)


def f2():
    for j in range(5):
        time.sleep(1)
        print('测试代码...', j)


pid = os.fork()

if pid < 0:
    print("Create process failed!")
elif pid == 0:
    p = os.fork()  # 二级子进程
    if p == 0:
        f2()  # 二级子进程执行
    else:
        os._exit(0)
else:
    os.wait()
    f1()
