#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
"""僵尸进程"""
import os

pid = os.fork()

if pid < 0:
    pass
elif pid == 0:
    print("Child process...\n Pid =", os.getpid())
else:
    while True:
        pass
