#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
import os
from time import *

pid = os.fork()

if pid < 0:
    print("Create process failed!")
elif pid == 0:
    # sleep(2) #  父提前结束
    print("Child process...\n Pid =", os.getpid())
    print("Get parent Pid =", os.getppid())
else:
    print("Parent process...\n Pid =", os.getpid())
    print("Get child Pid =", pid)
