#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
"""信号方法处理僵尸"""
import os
import signal

# 处理子进程退出
signal.signal(signal.SIGCHLD, signal.SIG_IGN)
pid = os.fork()

if pid < 0:
    print("Create process failed!")
elif pid == 0:
    print("Child process...\n Pid =", os.getpid())
    print("Get parent Pid =", os.getppid())
else:
    print("Parent process...\n Pid =", os.getpid())
    print("Get child Pid =", pid)
    while True:
        pass
