#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
import os

pid = os.fork()

if pid < 0:
    pass
elif pid == 0:
    print("Child process...\n Pid =", os.getpid())
    os._exit(2)  # 会 x256
else:
    # pid, status = os.wait()  # 等待处理僵尸
    pid, status = os.waitpid(-1, os.WNOHANG)  # 非阻塞
    print('pid', pid)
    print('status', os.WEXITSTATUS(status))
    while True:
        pass
