#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
# 手动创建corpus语料库目录，modify目录
import re

for i in range(1, 49):  # 49指文档的数量
    with open(f"./corpus/{i}.txt", encoding='utf-8') as file:  # 循环打开所有文档
        data = file.read().lower()  # 将字母改为小写
        if "community with a shared future" in data:
            pattern_1 = re.compile(r'community with a shared future.{0,10}for', re.S)  # 查找以for为关键词的典型共现
            pattern_2 = re.compile(r'community with a shared future.{0,10}in', re.S)
            modify_1 = pattern_1.findall(data)  # 寻找以for为关键词的典型共现
            modify_2 = pattern_2.findall(data)
            for item in modify_1:
                item2 = item.replace("for", "")  # 删除典型共现
                data = data.replace(item, item2)
            for item in modify_2:
                item2 = item.replace("in", "")
                data = data.replace(item, item2)
            with open(f"./modify/{i}.txt", "w", encoding="utf-8") as fl:  # 保存修改后的文件
                fl.write(data)
print("Finish!")
