#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
from pymysql import *


class MysqlPython:
    def __init__(self, host, port, db, user, passwd, charset='utf8'):
        self.cursor = None
        self.connect = None
        self.host = host
        self.port = port
        self.db = db
        self.user = user
        self.passwd = passwd
        self.charset = charset

    def open(self):
        self.connect = connect(host=self.host, port=self.port, db=self.db,
                               user=self.user, password=self.passwd,
                               charset=self.charset)
        self.cursor = self.connect.cursor()

    def close(self):
        self.cursor.close()
        self.connect.close()

    def run(self, sql):
        self.open()
        self.cursor.execute(sql)
        self.connect.commit()
        self.close()
        print('OK!')

    def display(self):
        for i in self.cursor.fetchall():
            print(i)
