#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
from sql_class import MysqlPython

sqlh = MysqlPython(host="39.99.32.138", user="", port=3306,
                   passwd="", db='project1', charset='utf8')

sqlh.run("select * from project1.city;")
sqlh.display()
