#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
from bs4 import BeautifulSoup

data = BeautifulSoup(open('orig_web_data/Comoros.html', 'r', encoding='utf-8'), 'lxml')
web_data = []
try:
    for item in data.find_all('li'):
        if item.find('h3'):
            if item.p:
                temp = item.p.text
            else:
                temp = ''
            web_data.append([item.h3.a.text, item.h3.a['href'], temp])
except AttributeError as e:
    print(e)
finally:
    with open('./African_website/Comoros.tsv', 'w', encoding='utf-8') as f:
        f.write('Title|URL|Description\n')
        for item in web_data:
            f.write(item[0] + '|' + item[1] + '|' + item[2] + '\n')

# print(orig_web_data.find('li'), end='\n')
# print(orig_web_data.find('li').text, end='\n')
# print(orig_web_data.find('li').a, end='\n')
# print(orig_web_data.find('li').h3, end='\n')
# print(orig_web_data.find('li').h3.a, end='\n')
# print(orig_web_data.find('li').h3.a['href'], end='\n')
