#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
# num = 9852
# a = num // 100
# num = num - 100 * a
# b = num // 50
# num = num - 50 * b
# c = num // 20
# num = num - 20 * c
# d = num // 10
# num = num - 10 * d
# e = num
# print(a, b, c, d, e)


def num_1(num, mianzhi):
    count_1 = num // mianzhi
    num_1 = num - mianzhi * count_1
    return num_1, count_1


num = 9852
num, a = num_1(num, 100)
num, b = num_1(num, 50)
num, c = num_1(num, 20)
num, d = num_1(num, 10)
num, e = num_1(num, 1)
print(a, b, c, d, e)
