#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-


def mother(y):
    def f(x):
        temp = x ** y
        return temp

    return f


def deco(fn):
    def f(func, number):
        print("+++++")
        temp = fn(func, number)
        print(temp)
        print("-----")

    return f


bi = mother(2)
tri = mother(3)

print(bi(3))
print(tri(3))


@deco
def play(func, number):
    temp = func(number)
    return temp


play(bi, 3)