#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import os
from multiprocessing import Process
from time import sleep

filename = "./1.jpg"
size = os.path.getsize(filename)


# 复制上半部分
def top():
    f = open(filename, 'rb')
    n = size // 2
    fw = open("2.jpg", 'wb')
    fw.write(f.read(n))
    f.close()
    fw.close()


# 下半部分
def bot():
    sleep(1)
    f = open(filename, 'rb')
    fw = open('3.jpg', 'wb')
    f.seek(size // 2, 0)
    while True:
        data = f.read()
        if not data:
            break
        fw.write(data)
    f.close()
    fw.close()


def main():
    t = Process(target=top)
    b = Process(target=bot)
    t.start()
    b.start()
    t.join()
    b.join()


if __name__ == '__main__':
    main()
