#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
import os
from os import fork
from time import sleep


def fun():
    """子进程函数"""
    print('子进程开始执行')
    sleep(2)
    print('子进程执行结束')


p = fork()
if p == 0:
    fun()
    os._exit()
else:
    os.wait()
