#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
# 管道通信
import os
import time
from multiprocessing import Process, Pipe

# 创建管道
fd1, fd2 = Pipe()


def fun(name):
    time.sleep(1)
    # 向管道写入内容
    fd1.send({name: os.getpid()})


def main():
    jobs = []
    for i in range(5):
        p = Process(target=fun, args=(i,))
        jobs.append(p)
        p.start()

    for i in range(5):
        data = fd2.recv()
        print(data)

    for i in jobs:
        i.join()


if __name__ == '__main__':
    main()
