#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
# 向进程池添加事件
from multiprocessing import *
from time import sleep


def worker(msg):
    sleep(1)
    print(msg)


if __name__ == '__main__':
    # 创建进程池
    pool = Pool()

    for i in range(20):
        msg = "Hello %d" % i
        r = pool.apply_async(func=worker, args=(msg,))
    # 关闭进程池
    pool.close()
    # 回收进程池
    pool.join()
    print(r.get())

