#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
import multiprocessing as mp
from time import sleep


def fun():
    """子进程函数"""
    print('子进程开始执行')
    sleep(2)
    print('子进程执行结束')


if __name__ == '__main__':
    # 创建进程对象
    p = mp.Process(target=fun)

    # 启动进程
    p.start()

    sleep(2)
    print('父进程干点事')
    # 回收进程
    p.join()
