#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import time
from multiprocessing import Value, Process
from random import *

money = Value('i', 5000)


# 操作共享内存
def man():
    for i in range(30):
        time.sleep(.2)
        money.value += randint(1, 1000)


def girl():
    for i in range(30):
        time.sleep(.15)
        money.value -= randint(100, 800)


m = Process(target=man)
g = Process(target=girl)
m.start()
g.start()
m.join()
g.join()
# 获取共享内存值
print("一月余额:", money.value)
