#  Copyright (c) 2022. Generated by Gu.
# 对于第n个台阶来说，只能从n-1或者n-2的台阶跳上来，所以F(n) = F(n-1) + F(n-2)，看到这儿就熟悉了吧，这不就是斐波拉契数列嘛
# class Solution:
#     def jump_floor(self, number):
#         # write code here
#         res = [1, 2]
#         while len(res) <= number:
#             res.append(res[-1] + res[-2])
#             print(res)
#         return res[number - 1]
#
#
# a = Solution()
# print(a.jump_floor(5))


def jumpfrog(n):
    if n == 1:
        print(n)
        return 1
    elif n == 2:
        print(n)
        return 2
    elif n > 2:
        print(n)
        return jumpfrog(n - 1) + jumpfrog(n - 2)


print(jumpfrog(5))
