#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import random
from time import sleep

import requests


class Spider:
    def __init__(self):
        self.headers = {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"}
        self.path = r'../ScienceDirect_Spider/'

    def parse_url(self, title: str, url: str) -> None:
        """send request to get html and save it.

        Args:
            title: 标题
            url: 链接
        """
        requests.session().keep_alive = False
        print(title, url)
        response = requests.get(url, headers=self.headers)
        # sleep(random.randint(0, 2))
        file_path = f"{title}.html"
        with open(file_path, "w", encoding="UTF-8") as f:
            f.write(response.content.decode())


if __name__ == '__main__':
    Spider().parse_url("test", "https://www.sciencedirect.com/journal/the-crop-journal/vol/11/issue/5")
