#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
def my_range(stop):
    start = 0
    while start < stop:
        # 生成器 告诉 客户端代码 的结果是右边item
        # 客户端代码 告诉 生成器 的结果是左边value
        value = yield start
        print('生成器收到：', value)
        start += 1


if __name__ == '__main__':
    iter = my_range(5)
    print(iter.__next__())
    while True:
        try:
            item = iter.send('msg')
            print(item)
        except:
            break
