#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
class MyRangeIterator:
    def __init__(self, count):
        self.start = -1
        self.stop = count

    def __next__(self):
        if self.start < self.stop - 1:
            self.start += 1
            return self.start
        else:
            raise StopIteration


class MyRange:
    def __init__(self, stop):
        self.stop = stop

    def __iter__(self):
        return MyRangeIterator(self.stop)


if __name__ == '__main__':
    iterator = MyRange(5)
    for item in iterator:
        print(item)
