#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
class MyGenerator:
    def __init__(self, target):
        self.target = target
        self.index = 0

    def __iter__(self):
        return self

    def __next__(self):
        if self.index > len(self.target) - 1:
            raise StopIteration()
        temp = self.index
        self.index += 1
        return self.target[temp]


if __name__ == '__main__':
    for item in MyGenerator([3, 4, 4, 5, 7]):
        print(item)
    print('\n')
    iterator = MyGenerator([3, 4, 4, 5, 7])
    while True:
        try:
            item = next(iterator)
            print(item)
        except StopIteration:
            break
