#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
from socket import *
from time import sleep

# 广播地址
dest = ('192.168.0.255', 9999)

s = socket(AF_INET, SOCK_DGRAM)

s.setsockopt(SOL_SOCKET, SO_BROADCAST, 1)

data = """
    5.22 陕西 杨凌
"""

try:
    while True:
        sleep(2)
        s.sendto(data.encode(), dest)
except KeyboardInterrupt:
    s.close()
