#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
from socket import *


def handle(connfd):
    """处理浏览器http请求"""
    print('Request from:', connfd.getpeername())
    request = connfd.recv(4096)  # 接收http请求
    # 防止客户端断开
    if not request:
        return
        # 按行分割request
    request_line = request.splitlines()[0].decode()
    info = request_line.split(' ')[1]
    if info == '/':
        with open('index.html', encoding='utf-8') as f:
            response = 'HTTP/1.1 200 OK\r\n'
            response += 'Content-Type:text/html\r\n'
            response += '\r\n'
            response += f.read()
    else:
        response = 'HTTP/1.1 404 Not Found\r\n'
        response += 'Content-Type:text/html\r\n'
        response += '\r\n'
        response += "<h1>Sorry...<h1>"
    connfd.send(response.encode())  # 向浏览器发送信息


def main():
    socked = socket()
    socked.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
    socked.bind(('0.0.0.0', 8888))
    socked.listen(3)
    print("Listening the port 8888...")
    while True:
        connfd, addr = socked.accept()
        handle(connfd)
        connfd.close()


if __name__ == '__main__':
    main()
