#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
from socket import *

# 服务器地址
# host = '0.0.0.0'
host = '127.0.0.1'
port = 8888
addr = (host, port)

# 创建套接字
sockfd = socket(AF_INET, SOCK_DGRAM)

# 收发消息
while True:
    data = input('Msg:')
    if not data:
        break
    sockfd.sendto(data.encode(), addr)
    msg, addr1 = sockfd.recvfrom(1024)
    print(f'From server {addr1}:', msg.decode())

# 关闭套接字
sockfd.close()
