#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
import socket

# 创建流式套接字
sockfd = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# 绑定地址
sockfd.bind(('0.0.0.0', 8888))

# 设置监听
sockfd.listen(5)

# 等待处理客户端链接
while True:
    print('Waiting for connect...')
    try:
        connfd, addr = sockfd.accept()
        print('Connect from:', addr)
    except KeyboardInterrupt:
        print('Exit service.')
        break

    # 收发消息
    while True:
        data = connfd.recv(1024)
        # 空则退出
        if not data:
            break
        print('Received messages:', data.decode())
        n = connfd.send(b'Receive your message.')
        print('%d bytes of data were sent' % n)
    connfd.close()

# 关闭套接字
sockfd.close()
