#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
from socket import *

host = '0.0.0.0'

# 创建数据报套接字
sockfd = socket(AF_INET, SOCK_DGRAM)

# 绑定地址
server_addr = (host, 8888)
sockfd.bind(server_addr)
try:
    # 收发消息
    while True:
        data, addr = sockfd.recvfrom(1024)
        print('Received messages:', data.decode())
        sockfd.sendto(b'Thanks!', addr)
except KeyboardInterrupt:
    # 关闭套接字
    sockfd.close()
