#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
filename = input('Filename:')

try:
    fr = open(filename, 'rb')
except FileNotFoundError as e:
    print(e)
else:
    fw = open('my_file', 'wb')
    while True:
        data = fr.read(1024)
        if not data:
            break
        fw.write(data)

    fw.close()
    fr.close()
