#  Copyright (c) 2022. Generated by Gu.
import numpy as np


def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x


def bogosort(x):
    while np.any(x[:-1] > x[1:]):
        np.random.shuffle(x)
    return x


x = np.array([2, 1, 4, 3, 5])
# selection_sort(x)
bogosort(x)
