#  Copyright (c) 2022. Generated by Gu.
# 你可以用这些方法有效地将数据进行区间划分并手动创建直方图。例如,假定我们有1000
# 个值,希望快速统计分布在每个区间中的数据频次,可以用ufunc.at来计算:
import numpy as np
from matplotlib import pyplot as plt

np.random.seed(42)
x = np.random.randn(100)

# 手动计算直方图
bins = np.linspace(-5, 5, 20)
counts = np.zeros_like(bins)

# 为每个x找到合适的区间
i = np.searchsorted(bins, x)

# 为每个区间加上1
np.add.at(counts, i, 1)

# 画出结果
plt.plot(bins, counts, drawstyle='steps', linestyle='dotted')
plt.show()

plt.hist(x, bins, histtype='step')
plt.show()
