#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
"""
    界面视图类
"""
import os

from GameCoreController import GameCoreController
from GamrCoreModel import Direction


class GameConsoleView:
    """
        控制台视图
    """

    def __init__(self):
        # Creating core class objects
        self.__controller = GameCoreController()

    def start(self):
        """
            game start
        :return: None
        """
        self.__controller.generate_new_number()
        self.__controller.generate_new_number()
        self.__print_matrix()

    def __print_matrix(self):
        """
            display matrix
        :return:None
        """
        os.system('clear')
        print('----------')
        self.__controller.display()
        print('----------')

    def update(self):
        """
            Update game logic
        :return:None
        """
        while True:
            self.__move_matrix()
            if self.__controller.is_change:
                self.__controller.generate_new_number()
                self.__print_matrix()
                if self.__controller.is_game_over():
                    print('游戏结束!')
                    raise SystemExit

    def __move_matrix(self):
        msg = input('请输入移动方向(w s a d)')
        if msg == 'w':
            self.__controller.move(Direction.up)
        elif msg == 's':
            self.__controller.move(Direction.down)
        elif msg == 'a':
            self.__controller.move(Direction.left)
        elif msg == 'd':
            self.__controller.move(Direction.right)
        else:
            print('请重新输入！')
