#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import os
import pandas as pd
import xlwings as xw

# 定义输入文件夹和输出文件夹的路径
tsv_folder = './tsv'
xlsx_folder = './xlsx'

# 确保输出文件夹存在，如果不存在则创建它
os.makedirs(xlsx_folder, exist_ok=True)

# 获取输入文件夹中的所有.tsv文件
tsv_files = [f for f in os.listdir(tsv_folder) if f.endswith('.tsv')]

# 循环处理每个.tsv文件
for tsv_file in tsv_files:
    print("正在进行:", tsv_file)
    # 构建完整的输入文件路径和输出文件路径
    tsv_file_path = os.path.join(tsv_folder, tsv_file)
    xlsx_file_path = os.path.join(xlsx_folder, os.path.splitext(tsv_file)[0] + '.xlsx')

    # 读取.tsv文件到pandas DataFrame
    df = pd.read_csv(tsv_file_path, sep='\t')

    # 创建一个新的Excel工作簿
    wb = xw.Book()

    # 选择默认的Sheet
    sheet = wb.sheets['Sheet1']

    # 将DataFrame写入Excel工作簿
    sheet.range('A1').value = df.values

    # 保存Excel文件为.xlsx格式
    wb.save(xlsx_file_path)

    # 关闭工作簿
    wb.close()

print("转换完成！")
