#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
def f(x):  # 原函数
    return 2 * (x ** 3) - 4 * (x ** 2) + 3 * x - 6


def g(x):  # 原函数求导
    return 6 * (x ** 2) - 8 * x + 3


x = 1.5
while 1:
    a = x
    x = x - f(x) / g(x)
    if abs(x - a) < 1e-5:  # abs()函数返回绝对值，1e-5为10的负5次方
        break
print("方程的解为：%.1f" % x)
