#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
# 有15个基督徒和15个非基督徒在海上遇险，为了能让一部分人活下来不得不将其中15个人扔到海里面去，有个人想了个办法就是大家围成一个圈，由某个人开始从1报数，
# 报到9的人就扔到海里面，他后面的人接着从1开始报数，# 报到9的人继续扔到海里面，直到扔掉15个人。由于上帝的保佑，15个基督徒都幸免于难，问这些人最开始是
# 怎么站的，哪些位置是基督徒哪些位置是非基督徒。输出最后站位，用1表示是基督徒，0表示非基督徒；
def josephus(n, k):
    # n代表总人数，k代表报数的数字
    lst = [x for x in range(1, n + 1)]
    index = 0
    while True:
        temp = lst.pop(0)
        index += 1
        if index == k:
            index = 0
            continue
        lst.append(temp)
        if len(lst) == 15:
            return lst


print(josephus(30, 9))
L1 = ['0'] * 30
for x in josephus(30, 9):
    L1[x - 1] = '1'
print(L1)
