#  Copyright (c) 2022. Generated by Gu.
#  不知道哪里出了bug，不管了-_-
class Human:
    total_count = 0

    def __init__(self, n, a, add='未填写'):
        self.name = n
        self.age = a
        self.address = add
        self.__class__.total_count += 1

    def __del__(self):
        self.__class__.total_count -= 1

    def show_info(self):
        print(self.name, '今年', self.age, '岁,家庭住址', self.address)

    def update_age(self):
        self.age += 1

    @classmethod
    def get_human_count(cls):
        return Human.total_count


def input_human():
    ls = []
    while True:
        name = input('请输入姓名：')
        if not name:
            break
        age = int(input('请输入年龄:'))
        addr = input('请输入家庭住址:')
        ls.append(Human(name, age, addr))
    return ls


def main():
    docs = input_human()
    print('当前的总人数是', Human.get_human_count())
    for h in docs:
        h.show_info()
    for h in docs:
        h.update_age()
    for h in docs:
        h.show_info()


if __name__ == '__main__':
    main()
