#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-

def show_menu():
    print('1)添加学生信息')
    print('2)显示所生的信息')
    print('3)删除学生信息')
    print('4)修改学生成绩')
    print('5)按学生成绩高-低显示学生信息')
    print('5)按学生成绩低-高显示学生信息')
    print('7)按学生年龄高-低显示学生信息')
    print('8)按学生年龄低-高显示学生信息')
    print('q)退出')


def input_student():
    lst = []
    while True:
        n = input("请输入姓名：")
        if not n:
            break
        a = input("请输入年龄：")
        s = input("请输入成绩：")
        d = {'name': n,
             'age': a,
             'score': s
             }
        lst.append(d)
    return lst


def output_students(lst):
    print("+-----------+--------+---------+")
    print("|   name    +  age   +  score  +")
    print("+-----------+--------+---------+")
    for d in lst:
        info = "| %9s | %6s | %7s |" % (d['name'], d['age'], d['score'])
        print(info)
    print("+-----------+--------+---------+")


def main():
    docs = []
    while True:
        show_menu()
        s = input("请选择")
        if s == 'q':
            return
        if s == '1':
            docs += input_student()
        elif s == '2':
            output_students(docs)


if __name__ == '__main__':
    main()
