#  Copyright (c) 2022. Generated by Gu.
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.datasets import load_digits
from sklearn.manifold import Isomap

sns.set()

digits = load_digits(n_class=6)
fig, ax = plt.subplots(8, 8, figsize=(6, 6))
for i, axi in enumerate(ax.flat):
    axi.imshow(digits.images[i], cmap='binary')
    axi.set(xticks=[], yticks=[])
plt.show()

# 用IsoMap方法将数字投影到二维空间
iso = Isomap(n_components=2)
projection = iso.fit_transform(digits.data)

# 离散型颜色条来显示结果，调整 ticks 与 clim 参数来改善颜色条
# 画图
plt.scatter(projection[:, 0], projection[:, 1], lw=0.1,
            c=digits.target, cmap=plt.cm.get_cmap('cubehelix', 6))
plt.colorbar(ticks=range(6), label='digit value')
plt.clim(-0.5, 5.5)
plt.show()
