#  Copyright (c) 2022. Generated by Gu.
import json
import re
from pprint import pprint

from parse_url import parse_url

url = "http://36kr.com"
html_str = parse_url(url)

ret = re.findall("<script>var props=(.*?)l, Locationnal=", html_str)[0]
with open("36kr.json", "w", encoding="utf-8") as f:
    f.write(ret)

ret = json.loads(ret)
pprint(ret)
