#  Copyright (c) 2022. Generated by Gu.
import json
from pprint import pprint

from parse_url import parse_url

url = "https://m.douban.com/rexxar/api/v2/subject_collection/tv_domestic/items?start={}&count=18"
# "Referer": "https://m.douban.com/tv/american"加入headers
html_str = parse_url(url)

ret1 = json.loads(html_str)
pprint(ret1)
