#  Copyright (c) 2022. Generated by Gu.
import requests
from retrying import retry

# headers = {"User-Agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Mobile Safari/537.36"}
headers = {
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"}


@retry(stop_max_attempt_number=3)  # 出现异常后继续重试三次
def _parse_url(url, method, data, proxies):
    if method == "POST":
        response = requests.post(url, proxies, datas=data, headers=headers)
    else:
        response = requests.get(url, proxies, headers=headers, timeout=3)
    assert response.status_code == 200
    return response.content.decode()


def parse_url(url, method="GET", data=None, proxies={}):
    try:
        html_str = _parse_url(url, method, data, proxies)
    except:
        html_str = None
    return html_str


if __name__ == '__main__':
    url1 = "http://www.baidu.com"
    print(parse_url(url1))
