#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import logging
import os

import pysentiment2 as ps


class Sentiment:
    def __init__(self):
        self.data_folder = "./Zheng He"
        self.result_file = "result.tsv"
        self.all_data = []
        self.logger = self.log()

    @staticmethod
    def log():
        """log"""
        logger = logging.getLogger()
        logger.setLevel(logging.INFO)
        fh = logging.FileHandler("log.log", mode='a', encoding="UTF-8")
        sh = logging.StreamHandler()  # 创建日志处理器，在控制台打印
        formatter = logging.Formatter('[%(asctime)s] [%(levelname)s] %(message)s', '%Y-%m-%d %H:%M:%S')
        fh.setFormatter(formatter)
        sh.setFormatter(formatter)
        logger.addHandler(fh)
        logger.addHandler(sh)
        logger.info("log init")
        return logger

    def main(self):
        temp = [f for f in os.listdir(self.data_folder) if f.endswith('.txt')]
        hiv4 = ps.HIV4()

        for item in temp:
            title = item.split('.')[0]
            with open(f"{self.data_folder}\\{item}", 'r', encoding='utf-8') as f:
                self.logger.info(f"Working: {item}")
                data = f.read()
                tokens = hiv4.tokenize(data)
                score = hiv4.get_score(tokens)
                self.all_data.append([title, score])
            self.logger.info(f"Finish: {item}")

        with open(f"./{self.result_file}", "a", encoding="utf-8") as fl:
            fl.write("File\tPositive\tNegative\tPolarity\tSubjectivity\n")
            for item in self.all_data:
                fl.write(
                        f"{item[0]}\t{item[1]['Positive']}\t{item[1]['Negative']}\t{item[1]['Polarity']}\t{item[1]['Subjectivity']}\n")
        self.logger.info(f"All Done!")


if __name__ == '__main__':
    Sentiment().main()
