#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
class AgeException(Exception):
    """
        封装错误信息
    """

    def __init__(self, msg, code, age_value):
        super().__init__(msg)
        self.msg = msg
        self.code = code
        self.age_value = age_value
