#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import os
import re

from bs4 import BeautifulSoup


class Finder:
    def __init__(self):
        self.data_folder = ""
        self.result_folder = ""
        self.result_file = "result.tsv"
        self.owner = True  # 0 修改

    def is_owner(self):
        if self.owner:
            self.data_folder = "./data"
            self.result_folder = "./result"
        else:
            self.data_folder = "./data_title_lyx"  # 1 修改
            self.result_folder = "./result_title_lyx"

    @staticmethod
    def remove_garbled_characters(text):
        pattern = re.compile(r'[^\x00-\x7F]+')  # 定义正则表达式，用于匹配乱码字符
        result = re.sub(pattern, ' ', text)  # 使用空字符串替换乱码字符
        return result

    def method(self):
        self.is_owner()
        html_files = [f for f in os.listdir(self.data_folder) if f.endswith('.html')]
        # os.remove(f"{self.result_folder}/{self.result_file}")
        for html_file in html_files:
            with open(f"{self.data_folder}/{html_file}", "r", encoding='utf-8') as f:
                orig_data = f.read()
                orig_data = re.sub(r"&amp;nbsp;×&amp;nbsp;", " x ", orig_data)
                orig_data = re.sub(r"&nbsp;", " ", orig_data)
                orig_data = self.remove_garbled_characters(orig_data)
                data = BeautifulSoup(orig_data, 'lxml')
                print("File：", html_file)
                web_data = []
                temp = data.find("h3", "js-issue-status").text
                current_year = re.search(r"2\d\d\d", temp).group()
                try:
                    for item in data.find_all('dt'):
                        if item.h3.a.span.text == "Editorial Board":
                            continue
                        if item.h3.a.span.text == "EDITORIAL BOARD":
                            continue
                        web_data.append([item.h3.a.span.text, "https://www.sciencedirect.com" + item.h3.a['href'],
                                         current_year])
                except AttributeError as e:
                    print(e)
                finally:
                    with open(f'{self.result_folder}/{self.result_file}', 'a', encoding='utf-8') as f:
                        for item in web_data:
                            f.write(item[0] + '\t' + item[1] + '\t' + str(item[2]) + '\n')


if __name__ == '__main__':
    Finder().method()
