#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import sys
import time
from socket import *


class FTPClient:
    def __init__(self, sockfd: socket):
        self.sockfd = sockfd

    def do_list(self):
        self.sockfd.send(b'L')
        data = self.sockfd.recv(128).decode()
        if data == "OK":
            data = self.sockfd.recv(128)
            print(data.decode())
        else:
            print(data)

    def do_quit(self):
        self.sockfd.send(b'Q')
        self.sockfd.close()
        sys.exit("谢谢使用")

    def do_get(self, name):
        self.sockfd.send(('G ' + name).encode())
        data = self.sockfd.recv(128).decode()
        if data == 'OK':
            with open(name, 'wb') as fd:
                while True:
                    data = self.sockfd.recv(1024)
                    if data == b'##':
                        break
                    fd.write(data)
        else:
            print(data)

    def do_put(self, name):
        """上传文件"""
        try:
            f = open(name, 'rb')
        except Exception:
            print("没有该文件")
            return
        name = name.split('/')[-1]
        self.sockfd.send(('P ' + name).encode())
        data = self.sockfd.recv(128).decode()
        if data == 'OK':
            while True:
                data = f.read(1024)
                self.sockfd.send(data)
                if not data:
                    time.sleep(.1)
                    self.sockfd.send(b'##')
                    break
                self.sockfd.send(data)
            f.close()
        else:
            print(data)


def request(sockfd):
    ftp = FTPClient(sockfd)
    """发起请求"""
    while True:
        print("""********************""")
        print("""******* list *******""")
        print("""***** get file *****""")
        print("""***** put file *****""")
        print("""******* quit *******""")
        print("""********************""")

        cmd = input("输入命令：")
        if cmd.strip() == "list":
            ftp.do_list()
        elif cmd.strip() == "quit":
            ftp.do_quit()
        elif cmd[:3] == 'get':
            filename = cmd.strip().split(' ')[-1]
            ftp.do_get(filename)
        elif cmd[:3] == 'put':
            filename = cmd.strip().split(' ')[-1]
            ftp.do_put(filename)


def main():
    """网络连接"""
    ADDR = ('127.0.0.1', 8888)
    sockfd = socket()
    try:
        sockfd.connect(ADDR)
    except Exception as e:
        print("连接失败:", e)
        return
    else:
        print("""
        *******************
         Data  File  Image
        *******************
        """)
        cls = input("请输入文件种类：")
        if cls not in ['Data', 'File', 'Image']:
            print("输入错误")
            return
        else:
            sockfd.send(cls.encode())
            request(sockfd)  # 发送具体请求


if __name__ == '__main__':
    main()
