#  Copyright (c) 2022. Generated by Gu.
import re
import time

import pandas as pd
import requests
from requests.exceptions import RequestException


def get_one_page(url):
    """
    爬取某一页的源代码；
    url：当前网页的url；
    return：当前网页的html文本
    """
    try:
        # 输入你的代码，构造请求方法，获取服务器响应 r；
        r = requests.get(url)
        print(r.status_code)
        if r.status_code == 200:
            r.text.encode('utf-8')
            return r.text
        return None
    except RequestException as e:
        print(e)
        return None


def parse_one_page(html):
    """
    从当前网页中提取“排行榜号（list_num ）”，“书名”，“评论数量”，“推荐度”，
    “作者”、“出版社信息”、“原始价格”、“折后价格”，并存入字典中。
    """
    # 创建正则表达式对象，填充compile的第一个参数内
    pattern = re.compile(
        '<li>.*?list_num.*?(\d+).</div>.*?class="name".*?title="(.*?)">.*?class="star".*?target="_blank">(.*?)</a>.*?class="tuijian">(.*?)<.*?class="publisher_info">.*?target="_blank">(.*?)</a>.*?class="publisher_info">.*?target="_blank">(.*?)</a>.*?class="price_n">&yen;(.*?)</span>.*?class="price_r">&yen;(.*?)</span>.*?</li>',
        re.S)

    items = re.findall(pattern, html)
    for item in items:
        yield {
            'index': item[0],  # 排行榜号-你的表达式 ,
            'title': item[1],  # 书名-你的表达式,
            'reviews': item[2],  # 评论数量-你的表达式,
            'recommends': item[3],  # 推荐度-你的表达式,
            'authors': item[4],  # 作者名-你的表达式,
            'publisher': item[5],  # 出版社-你的表达式
            'price_n': item[6],  # 折后价格-你的表达式,
            'price_r': item[7]  # 折前价格-你的表达式，
            }


def main(offset=1, file=open(r'dangdang_books.csv', 'a', encoding='utf-8')):
    """主函数
    offset：url的偏移量（从1到25）
    """
    url = 'http://bang.dangdang.com/books/bestsellers/01.00.00.00.00.00-24hours-0-0-1-' + str(offset)
    html = get_one_page(url)
    for item in parse_one_page(html):
        for value in item.values():
            file.write('"' + str(value) + '"' + ',')
        file.write('\n')
    file.close()


file = open(r'dangdang_books.csv', 'w', encoding='utf-8')
file.write('index,title,reviews,recommends,authors,price_n,price_r\n')
for i in range(1, 26):
    url = 'http://bang.dangdang.com/books/bestsellers/01.00.00.00.00.00-24hours-0-0-1-' + str(i)
    html = get_one_page(url)
    for item in parse_one_page(html):
        line = ''
        for value in item.values():
            line += '"' + str(value) + '"' + ','
        file.write(line.strip(',') + '\n')
    time.sleep(1)
file.close()

pd.read_csv(r'dangdang_books.csv', index_col=False)
