#  Copyright (c) 2022. Generated by Gu.
class Car:
    def __init__(self, c1):
        self.color = c1


car1 = Car('red')
print(dir(car1))
a = getattr(car1, 'color')
b = getattr(car1, 'brand', '没有brand属性')
print(a, b)

c = hasattr(car1, 'color')
d = hasattr(car1, 'brand')
print(c, d)

setattr(car1, 'brand', '比亚迪')
e = getattr(car1, 'brand', '没有brand属性')
print(e)
