#  Copyright (c) 2022. Generated by Gu.
class Human:
    def say(self, what):
        print('说', what)

    def walk(self, distance):
        print('走了', distance, '公里')


class Student(Human):
    def study(self, subject):
        print('正在学习', subject)


class Teacher(Student):
    def teach(self, that):
        print('老师正在教', that)


t1 = Teacher()
t1.say('今天早点下班')
t1.walk(1)
t1.teach('面向对象')
