#  Copyright (c) 2022. Generated by Gu.
# 此示例示意多继承
class Car:
    def run(self, speed):
        print("汽车以", speed, "km/h的速度行驶")


class Plane:
    def fly(self, height):
        print("飞机以海拔", height, "米的高度飞行")


class PlaneCar(Car, Plane):
    """飞行汽车类"""
    pass


p1 = PlaneCar()
p1.fly(10000)
p1.run(299)


class X(object):
    pass


class Y(object):
    pass


class A(X, Y):
    pass


class B(Y):
    pass


class C(A, B):
    pass


print(C.__mro__)
for x in C.__mro__:
    print(x)
