#  Copyright (c) 2022. Generated by Gu.
def mycp(src_file, dst_file):
    """
    src_file 源文件名
    dst_file 目标文件名
    """
    try:
        with open(src_file, 'rb') as fr, \
                open(dst_file, 'wb') as fw:
            while True:
                s = fr.read(4096)  # 文件过大分批传输
                if not s:  # 无字节串停止
                    break
                fw.write(s)
    except:
        return False

    return True


def main():
    src = input("请输入源文件名：")
    dst = input("请输入目标文件名：")
    if mycp(src, dst):
        print("复制文件成功")
    else:
        print("复制文件失败")


if __name__ == '__main__':
    main()
