#  Copyright (c) 2022. Generated by Gu.
class A:
    def work(self):
        print("A类的work方法被调用")


class B(A):
    def work(self):
        print("B类的work方法被调用")


b = B()
b.work()  # 调用谁?
A.work(b)  # 调用A中方法
