#  Copyright (c) 2022. Generated by Gu.
class Human:
    def __init__(self, n, a):
        self.name = n
        self.age = a
        print('Human类的__init__被调用')

    def show_info(self):
        print('姓名', self.name)
        print('年龄', self.age)


class Student(Human):
    # pass
    def __init__(self, n, a, s=0):
        super().__init__(n, a)  # 显式调用基类的初始化方法
        self.score = s  # 学生类专属
        print('student类的__init__被调用')

    def show_info(self):
        super(Student, self).show_info()
        print('成绩', self.score)


s1 = Student('小明', 12)
s1.show_info()
