#  Copyright (c) 2022. Generated by Gu.
class A:
    def work(self):
        print("A类的work方法被调用")


class B(A):
    def work(self):
        print("B类的work方法被调用")

    def doworks(self):
        self.work()  # 调用B中方法
        super(B, self).work()  # 超类方法
        super().work()  # 超类方法
        # super(__class__, self).work()


b = B()
b.work()  # 调用B中方法
print('以下用b调用覆盖版本的方法')
A.work(b)  # 调用A中方法
super(B, b).work()
b.doworks()
