#  Copyright (c) 2022. Generated by Gu.
class MyList:
    def __init__(self, iterable):
        self.data = [x for x in iterable]

    def __repr__(self):
        return 'MyList(%r) ' % self.data

    def __neg__(self):
        print('__neg__')
        return MyList([-x for x in self.data])


L1 = MyList([1, -2, 3, 4, 5])
print("L1=", L1)
L2 = -L1
print("L2=", L2)
