#  Copyright (c) 2022. Generated by Gu.


# 打开文件读取文件数据(try-finally来实现关闭文件)
# f = open('abcd.txt', 'rt')
# def read_file():
#     try:
#         try:
#             while True:
#                 s = f.readline()
#                 if not s:
#                     break
#                 int(input('请输入任意数字'))
#                 print(s)
#         finally:
#             f.close()
#     except IOError:
#         print('出现异常已捕获')
#     except ValueError:
#         print('出现异常已处理')


# 打开文件读取文件数据(try-finally来实现关闭文件)
def read_file():
    try:
        with open('abcd.txt') as f:
            while True:
                s = f.readline()
                if not s:
                    break
                int(input('请输入任意数字'))
                print(s)
            print('文件已关闭')
    except IOError:
        print('出现异常已捕获')
    except ValueError:
        print('出现异常已处理')


read_file()
print('程序结束')
