#  Copyright (c) 2022. Generated by Gu.
from selenium import webdriver

driver = webdriver.Chrome(executable_path=r"C: \Program Files\Google\Chrome\Application\Chromedriver")
driver = webdriver.Chrome(executable_path=r"C:\Program Files\Google\Chrome \Application\Chromedriver")
driver.get("https://www.zhihu.com/explore")

import time

driver = webdriver.Chrome(executable_path=r"C:\Program Files \Google\Chrome\Application\Chromedriver")
driver.get("https://www.zhihu. com/explore")
time.sleep(2)
print(driver.page_source)
driver.quit
