#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
import os

print(os.path.getsize('LStack.py'))
print(os.listdir())
print(os.path.exists('aa.txt'))
print(os.path.isfile('LStack.py'))
print(os.path.isdir('LStack.py'))
