#  Copyright (c) 2022. Generated by Gu.
# 线性表应用-->两个多项式相加 P81
from operator import itemgetter


class PolyList:
    """多项式顺序表类"""

    def __init__(self):
        self.data = []

    def add(self, e):
        """将多项式e添加到末尾"""
        self.data.append(e)

    def create_list(self, fname):
        """从fname文件中读取多项式数据并添加到data"""
        with open(fname, 'r') as fin:
            n = int(fin.readline().strip())
            for i in range(n):
                x = fin.readline().strip().split()
                self.data.append([float(x[0]), int(x[1])])

    def __len__(self):
        """代替函数getsize()"""
        return len(self.data)

    def __getitem__(self, item):
        return self.data[item]

    def get_data(self):
        """返回多项式列表"""
        return self.data

    def sort(self):
        """对data列表按指数递减排序"""
        self.data = sorted(self.data, key=itemgetter(1), reverse=True)

    def poly_add(self, b):
        """当前多项式与多项式b的相加运算"""
        c = PolyList()
        m = len(self.data)
        n = len(b)
        i, j = 0, 0
        while i < m and j < n:
            x, y = self.data[i], b[j]
            if x[1] > y[1]:  # 将较大指数的p添加到c中
                c.add(x)
                i += 1
            elif x[1] < y[1]:  # 将较大指数的q添加到c中
                c.add(y)
                j += 1
            else:
                k = x[0] + y[0]  # 指数相同，系数相加
                if k != 0:  # k没有约为0就添加至c
                    c.add([k, x[1]])
                i += 1
                j += 1
        while i < m:  # 将a剩下的添加至c
            x = self.data[i]
            c.add(x)
            i += 1
        while j < n:  # 将b剩下的添加至c
            y = b[j]
            c.add(y)
            j += 1
        return c


if __name__ == '__main__':
    with open("abc.out", "w+") as fout:
        p = PolyList()
        p.create_list("abc1.in")
        print("多项式1：", end=' ', file=fout)
        print(p.get_data(), file=fout)
        p.sort()
        print("排序后结果：", end=' ', file=fout)
        print(p.get_data(), file=fout)
        q = PolyList()
        q.create_list("abc2.in")
        print("多项式2：", end=' ', file=fout)
        print(q.get_data(), file=fout)
        q.sort()
        print("排序后结果：", end=' ', file=fout)
        print(q.get_data(), file=fout)
        r = p.poly_add(q)
        print("相加多项式：", end=' ', file=fout)
        print(r.get_data(), file=fout)
