#  Copyright (c) 2022. Generated by Gu.
class FileManage:
    def __init__(self, filename='a.txt'):
        self.file = open(filename, 'w')

    def writelines(self, string):
        self.file.write(string)
        self.file.write('\n')

    def __del__(self):
        """析构方法会在对象销毁前自动调用"""
        self.file.close()
        self.file.close()
        print('文件已关闭')


fm = FileManage()
fm.writelines("hello world")
fm.writelines("这是中文写的第二行")
