#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import time
from socket import *

with open('log.txt', 'a+') as f:
    sockfd = socket()
    sockfd.bind(('127.0.0.1', 8888))
    sockfd.listen(3)

    # 设置套接字为非阻塞
    # sockfd.setblocking(False)

    # 超时检测
    sockfd.settimeout(3)

    while True:
        print("Waiting for connect...", end='\r')
        try:
            connfd, addr = sockfd.accept()
        except (BlockingIOError, timeout) as e:
            time.sleep(2)
            f.write("%s:%s" % (time.ctime(), e))
            f.flush()
        else:
            data = connfd.recv(1024).decode()
            print(data)
