#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import gevent


def foo(a, b):
    print("Running foo...")
    gevent.sleep(2)
    print("Foo again")


def bar():
    print("Running bar...")
    gevent.sleep(3)
    print("Bar again")


f = gevent.spawn(foo, 1, "hello")
g = gevent.spawn(bar)
gevent.joinall([f, g])
