#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import gevent
from gevent import monkey

monkey.patch_all()

from socket import *


def handle(c: socket):
    while True:
        data = c.recv(1024)
        if not data:
            break
        print(data.decode())
        c.close()


s = socket()
s.bind(('127.0.0.1', 8888))
s.listen(5)
while True:
    c, addr = s.accept()
    print("Connect from", addr)
    # handle(c) 循环方案
    gevent.spawn(handle, c)

s.close()
