#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
from socket import *

from select import *

# 设置套接字为关注IO
s = socket()
s.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
s.bind(('127.0.0.1', 8888))
s.listen(5)

p = poll()

# 创建查找字典
fdmap = {s.fileno(): s}

# 设置关注IO
p.register(s, POLLIN | POLLERR)

# 循环监控
while True:
    events = p.poll()  # 阻塞等待IO发生
    for fd, event in events:
        if fd == s.fileno():
            c, addr = fdmap[fd].accept()
            print("Connect from", addr)
            # 添加新的关注事件
            p.register(c, POLLIN | POLLHUP)  # 读|断开连接
            fdmap[c.fileno()] = c
        elif event | POLLIN:
            data = fdmap[fd].recv(1024)
            if not data:
                print("Client Exit...")
                p.unregister(fd)
                fdmap[fd].close()
                del fdmap[fd]
                continue
            print(data.decode())
            fdmap[fd].send(b'OK')
