#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import signal
import sys
from socket import *
from multiprocessing import Process

# 创建监听套接字
HOST = "0.0.0.0"
PORT = 8888
ADDR = (HOST, PORT)

s = socket()  # TCP套接字
s.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
s.bind(ADDR)
s.listen(3)

# 僵尸进程处理
signal.signal(signal.SIGCHLD, signal.SIG_IGN)
print("Listen to the port 8888...")


def handle(c):
    """客户端处理函数"""
    print("客户端：", c.getpeername())
    while True:
        data = c.recv(1024)
        if not data:
            break
        print(data.decode())
        c.send(b'OK')
    c.close()


# 循环等待客户端连接
while True:
    try:
        c, addr = s.accept()
    except KeyboardInterrupt:
        sys.exit("Server Exit...")
    except Exception as e:
        print(e)
        continue

    # 创建新线程处理客户端请求
    p = Process(target=handle, args=(c,)) # 函数结束，子进程结束
    p.daemon = True  # 子进程随主进程退出
    p.start()
