#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
from socket import *

from select import select

# 设置套接字为关注IO
s = socket()
s.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
s.bind(('127.0.0.1', 8888))
s.listen(5)

# 设置关注的IO
rlist = [s]
wlist = []
xlist = []

while True:
    # 监控IO的发生
    print("Waiting...")
    rs, ws, xs = select(rlist, wlist, xlist, 5)
    # 遍历三个返回值列表，判断哪个IO发生
    for r in rs:
        if r is s:
            c, addr = s.accept()
            print("Connect from", addr)
            rlist.append(c)
        else:
            data = r.recv(1024)
            if not data:
                rlist.remove(r)
                r.close()
                continue
            print(data.decode())
            # r.send(b'OK')
            wlist.append(r)
    for w in ws:
        w.send(b'OK, Thanks!')
        wlist.remove(w)
    for x in xs:
        pass
