#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import sys
from socket import *

from select import select

fd = open('log.txt', 'a+')

sockfd = socket()
sockfd.bind(('127.0.0.1', 8888))
sockfd.listen(3)

print("开始提交监控的IO...")
rs, ws, xs = select([sockfd, fd], [fd], [], 3)
print(rs, ws, xs)

try:
    c, addr = sockfd.accept()
    while True:
        data = c.recv(1024)
        if not data:
            break
        print(data.decode())
        c.send(b'OK')
        c.close()
except KeyboardInterrupt:
    print('Quit!')
    sys.exit()
finally:
    fd.close()
