#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
import socket

# 创建TCP套接字
sockfd = socket.socket()

# 发起连接
server_addr = ('127.0.0.1', 8888)
sockfd.connect(server_addr)

# 收发消息
while True:
    data = input('Msg:')
    if not data:
        break
    sockfd.send(data.encode())
    data = sockfd.recv(1024)
    print('From server:', data.decode())

# 关闭套接字
sockfd.close()
