#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
from threading import Thread
from time import sleep


def fun():
    sleep(3)
    print("线程属性测试")


t = Thread(target=fun, name='has')
# t.daemon = True # 退出关系
t.start()

# 线程名称
# t.name = 'hh'
print("Thread name:", t.name)

# 线程生命周期
print("is alive:", t.is_alive())
print(t.daemon)
