#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
from socket import socket

s = socket()
s.connect(('127.0.0.1', 8888))
# s.connect(('192.168.0.190', 28888))  # 接收方

f = open('Picture_1.jpg', 'rb')

# 读取内容进行发送
while True:
    data = f.read(1024)  # 字节串
    if not data:
        break
    s.send(data)

f.close()
s.close()
