#  Copyright (c) 2022. Generated by Gu.
#  coding=utf-8
from SqList import SqList


def merge(a: SqList, b: SqList):
    c = SqList()
    i = j = 0
    while i < len(a) and j < len(b):
        if a[i] < b[j]:
            c.add(a[i])
            i += 1
        else:
            c.add(b[j])
            j += 1
    while i < len(a):
        c.add(a[i])
        i += 1
    while j < len(b):
        c.add(b[j])
        j += 1
    return c.display()


if __name__ == '__main__':
    ls1 = SqList()
    ls1.create_list([1, 2, 3, 5, 6])
    ls2 = SqList()
    ls2.create_list([0, 4, 7, 8, 9])
    ls1.display()
    ls2.display()
    merge(ls1, ls2)
