#  Copyright (c) 2022. Generated by Gu.
#  coding=utf-8
from SqList import SqList


def delete_1(ls: SqList(), x: int):
    k = 0
    for i in range(len(ls)):
        if ls[i] != x:
            ls[k] = ls[i]
            k += 1
    ls.size = k
    return ls.display()


def delete_2(ls: SqList(), x: int):
    k = 0
    for i in range(len(ls)):
        if ls[i] != x:
            ls[i - k] = ls[i]
        else:
            k += 1
    ls.size -= k
    return ls.display()


def delete_3(ls: SqList(), x: int):
    i = -1
    j = 0
    while j < len(ls):
        if ls[j] != x:
            i += 1
            if i != j:
                ls[i], ls[j] = ls[j], ls[i]
        j += 1
    ls.size = i + 1
    return ls.display()


if __name__ == '__main__':
    L = SqList()
    L.create_list([1, 2, 1, 5, 1])
    delete_1(L, 1)
    delete_2(L, 1)
    delete_3(L, 1)
