#  Copyright (c) 2022. Generated by Gu.
#  coding=utf-8
from SqList import SqList


def middle(a: SqList, b: SqList):
    i = j = k = 0
    while i < len(a) and j < len(b):
        k += 1
        if a[i] < b[j]:
            if k == len(a):
                return a[i]
            i += 1
        else:
            if k == len(b):
                return b[j]
            j += 1
