#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
from LinkStack import LinkStack


def reverse(st: LinkStack):
    """逆置栈st"""
    a = []
    while not st.empty():
        a.append(st.pop())
    for j in range(len(a)):
        st.push(a[j])
    return st
