#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
from LinkStack import LinkStack


def is_serial(a: list, b: list, n):
    """判断b是否是a的出栈序列, n为n个整数"""
    st = LinkStack()
    i, j = 0, 0
    while i < n:
        st.push(a[i])
        i += 1
        while not st.empty() and st.get_top() == b[j]:
            st.pop()
            j += 1
    return st.empty()


if __name__ == '__main__':
    n = 4
    a = [1, 2, 3, 4]
    b = [1, 3, 2, 4]
    if is_serial(a, b, n):
        print(b, "是合法的出栈序列")
    else:
        print(b, "不是合法的出栈序列")
    print("------" * n)
    c = [4, 3, 1, 2]
    if is_serial(a, c, n):
        print(c, "是合法的出栈序列")
    else:
        print(c, "不是合法的出栈序列")
