#  Copyright (c) 2022. Generated by Gu.
class SqStack:
    """顺序栈类"""

    def __init__(self):
        self.data = []

    def empty(self):
        """判断栈是否为空"""
        return len(self.data) == 0

    def push(self, e):
        """进栈 1"""
        self.data.append(e)

    def pop(self):
        """出栈 1"""
        assert not self.empty()
        return self.data.pop()

    def get_top(self):
        """取栈顶元素 1"""
        assert not self.empty()
        return self.data[-1]


if __name__ == '__main__':
    st = SqStack()
    st.push(1)
    st.push(2)
    st.push(3)
    st.push(4)
    print("出栈顺序:", end=' ')
    while not st.empty():
        print(st.pop(), end=' ')
    print()
