#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
from SqStack import SqStack


def is_palidrome(content: str):
    """判断是否为回文的算法"""
    st = SqStack()
    n = len(content)
    i = 0
    while i < n // 2:  # 将str前半字符进栈
        st.push(content[i])
        i += 1  # 继续遍历str
    if n % 2 == 1:  # n为奇数时
        i += 1  # 跳过中间的字符
    while i < n:  # 遍历str的后半字符
        if st.pop() != content[i]:
            return False  # 若str[i]不等于出栈字符返回False
        i += 1
    return True  # 是回文返回True


if __name__ == '__main__':
    str1 = 'abcba'
    print(is_palidrome(str1))
