#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
from SqStack import SqStack


def is_match(str):
    """判断表达式括号是否匹配"""
    st = SqStack()
    i = 0
    while i < len(str):
        e = str[i]
        if e == '(' or e == '[' or e == '{':
            st.push(e)
        else:
            if e == ')':
                if st.empty() or st.get_top() != '(':
                    return False
                st.pop()
            if e == ']':
                if st.empty() or st.get_top() != '[':
                    return False
                st.pop()
            if e == '}':
                if st.empty() or st.get_top() != '{':
                    return False
                st.pop()
        i += 1
    return st.empty()


if __name__ == '__main__':
    str1 = '([)]'
    if is_match(str1):
        print(str1 + '匹配')
    else:
        print(str1 + '不匹配')
    print('---------')
    str2 = '([])'
    if is_match(str2):
        print(str2 + '匹配')
    else:
        print(str2 + '不匹配')
