#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import re

s = """Hello world
你好，北京
"""

# # 只匹配ascii码字符
# regex = re.compile(r'\w+', flags=re.A)

# 忽略字母大小写
# regex = re.compile(r'[a-z]+', flags=re.I)

# .匹配换行
# regex = re.compile(r'.+', flags=re.S)

# 匹配每行开头结尾
# regex = re.compile(r'world$', flags=re.M)

# 正则添加注释
pattern = r"""\w+ # 第一部分
\s+ # 第二部分
\w+ # 第三部分
"""
regex = re.compile(pattern, flags=re.X | re.I)

l = regex.findall(s)
print(l)
