#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import re

s = "Levi:1994,Sunny:1993"
pattern = r"\w+:\d+"
# re模块调用
l = re.findall(pattern, s)
print(l)

s = "hello world how are you L-boby"
l = re.split(r'\W+', s)
print(l)

# 替换字符串
s = "时间: 2019/10/12"
ns = re.subn(r'/', '-', s)
print(ns)
