#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
from DisplaySchedule import PushSchedule
from Weather import Weather
from notify import PushQQ


class Push:
    """主入口"""

    def __init__(self, data):
        self.is_test = False
        self.data_temp = data  # 返回这一天的课表
        self.content = ''

    def judge(self):
        """判断是否处于测试模式"""
        if self.data_temp:
            self.is_test = True

    def main(self):
        """主函数"""
        self.judge()
        try:
            self.content += Weather().main()
            self.content += PushSchedule(self.data_temp).main()
        except Exception:
            self.content = "Oops, something went wrong. @梨堂落雨"
        finally:
            PushQQ(self.is_test, self.content).send()


if __name__ == '__main__':
    data_temp = ''
    Push(data_temp).main()
