#  Copyright (c) 2023. Generated by Gu.
#  -*- coding=utf-8 -*-
import requests


def send_1():
    p = 1332186865
    q = '祝您'
    temp = requests.get(
            url=f'http://127.0.0.1:8000/send_private_msg?user_id={p}&message={q}新年快乐鸭~ 祝你新的一年万事如意！')

    response = temp.json()
    print(response)


def send_2():
    push_config = {
            'HITOKOTO': False,  # 启用一言（随机句子）

            'GOBOT_URL': 'http://127.0.0.1:8000/send_private_msg',  # go-cqhttp
            # 推送到个人QQ：http://127.0.0.1/send_private_msg
            # 群：http://127.0.0.1/send_group_msg
            'GOBOT_QQ': 'user_id=1332186865',  # go-cqhttp 的推送群或用户
            # GOBOT_URL 设置 /send_private_msg 时填入 user_id=个人QQ
            #               /send_group_msg   时填入 group_id=QQ群
            'GOBOT_TOKEN': '',  # go-cqhttp 的 access_token
            }

    def go_cqhttp(title: str, content: str) -> None:
        """
        使用 go_cqhttp 推送消息。
        """
        print("go-cqhttp 服务启动")

        url = f'{push_config.get("GOBOT_URL")}?{push_config.get("GOBOT_QQ")}&message=标题:{title}\n内容:{content}'
        response = requests.get(url).json()

        if response["status"] == "ok":
            print("go-cqhttp 推送成功！")
        else:
            print("go-cqhttp 推送失败！")

    go_cqhttp('test', '尝试进行连接')


if __name__ == '__main__':
    send_1()
    send_2()
