#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
import time


def print_execute_time(func):
    def wrapper(*arg, **kwargs):
        start_time = time.time()
        result = func(*arg, **kwargs)
        execute_time = time.time() - start_time
        print('执行时间：', execute_time)
        return result

    return wrapper


class Student:
    def __init__(self, name):
        self.name = name

    @print_execute_time
    def study(self):
        print('开始学习啦！')
        time.sleep(2)


if __name__ == '__main__':
    s1 = Student('alice')
    s1.study()
