#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
"""
    员工管理器
"""


class Employee:
    pass
    # def __str__(self):
    #     print('员工')


class EmployeeManager:
    def __init__(self, employees):
        self.all_employee = employees
        self.index = 0

    def __iter__(self):
        self.index += 1
        return EmployeeIterator(self.all_employee)


class EmployeeIterator:
    def __init__(self, target):
        self.target = target
        self.index = 0

    def __next__(self):
        if self.index > len(self.target) - 1:
            raise StopIteration
        item = self.target[self.index]
        self.index += 1
        return item


class EmployeeManager2(EmployeeManager):
    def __init__(self, employees):
        super().__init__(employees)

    def __iter__(self):
        for i in self.all_employee:
            yield i


if __name__ == '__main__':
    manager = EmployeeManager([Employee(), Employee()])
    for item in manager:
        print(item)
    print('________________')
    manager2 = EmployeeManager2([Employee(), Employee()])
    for item in manager:
        print(item)
