#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
class Person:
    __slots__ = '__name', '__skills', '__dict__'

    def __init__(self, name: str):
        self.name = name
        self.__skills = []
        print(self.__slots__)
        print(self.__dict__)

    @property
    def name(self):
        return self.__name

    @name.setter
    def name(self, value):
        self.__name = value

    @property
    def skills(self):
        # return self.__skills 返回可变对象地址，类外仍可以操作可变对象
        return self.__skills[:]  # 返回新的可变对象地址，不影响类中的原对象

    def teach(self, people, skill: str):
        people.add_skills(skill)
        print(self.name, 'teach', people.name, skill)

    def add_skills(self, skill):
        self.__skills.append(skill)


if __name__ == '__main__':
    q = Person('hello')
    print(q.name)
