#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
class Student:
    """学生数据模型类: 此模块用来描述学生对象"""

    def __init__(self, num: int, name: str, sex: str, score: float):
        """
        学生对象
        :param name: 名字
        :param sex: 年龄
        :param score: 成绩
        :param num: 序号
        """
        self.num = num
        self.name = name
        self.sex = sex
        self.score = score

    def get_infos(self):
        return self.num, self.name, self.sex, self.score

    def __str__(self):
        return "我的编号是%-s号, 名字是%-s, 性别%-s, 成绩是%-s分。" % self.get_infos()

    def __repr__(self):
        return "Student1(num=%d, name='%s', age=%d, score=%d)" % self.get_infos()


def find_woman(target):
    for item in target:
        if item.sex == '女':
            yield item


def find_by_score(target):
    for item in target:
        if item.score > 90:
            yield item


if __name__ == '__main__':
    list_stu = [
        Student(28, 'aa', '男', 82),
        Student(25, 'bb', '女', 95),
        Student(26, 'cc', '女', 88),
        ]
    for item in find_woman(list_stu):
        print(item)
    print()
    for item in find_by_score(list_stu):
        print(item)
