#  Copyright (c) 2022. Generated by Gu.
#  -*- coding=utf-8 -*-
class Vector2:
    def __init__(self, x=0, y=0):
        self.x = x
        self.y = y

    @staticmethod
    def right():
        return Vector2(0, 1)

    @staticmethod
    def up():
        return Vector2(-1, 0)

    @staticmethod
    def left():
        return Vector2(0, -1)

    @staticmethod
    def down():
        return Vector2(1, 0)

    @staticmethod
    def right_up():
        return Vector2(-1, 1)


class DoubleListHelper:
    """                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    二维列表助手类
    """

    @staticmethod
    def get_elements(target: list, v_pos: Vector2, v_dir: Vector2, count: int) -> list:
        result = []
        for i in range(count):
            v_pos.x += v_dir.x
            v_pos.y += v_dir.y
            result.append(target[v_pos.x][v_pos.y])
        return result


if __name__ == '__main__':
    lst1 = [['00', '01', '02', '03'],
            ['10', '11', '12', '13'],
            ['20', '21', '22', '23']]

    r01 = DoubleListHelper.get_elements(lst1, Vector2(1, 0), Vector2.right(), 3)
    print(r01)
    r02 = DoubleListHelper.get_elements(lst1, Vector2(2, 3), Vector2.left(), 2)
    print(r02)
    r03 = DoubleListHelper.get_elements(lst1, Vector2(2, 0), Vector2.right_up(), 2)
    print(r03)
