#  Copyright (c) 2022. Generated by Gu.
import numpy as np

scores = np.loadtxt('jupyter/Numpy/data/2020期末成绩.csv', dtype=np.int32, delimiter='\t')
print(scores.shape)

import matplotlib.pyplot as plt

plt.figure(figsize=(6, 4), dpi=100)
x = scores[:, 0]
y = scores[:, 1]
plt.scatter(x, y, color='red')
plt.xlabel('《大学信息技术》成绩', fontproperties="SimHei", size=12)
plt.ylabel('《大学程序设计（Python）》成绩', fontproperties="SimHei", size=12)

from scipy import stats

cor, pv = stats.pearsonr(scores[:, 0], scores[:, 1])
print(f"皮尔逊相关系数：{cor}\n显著性检验水平：{pv}")
