#  Copyright (c) 2022. Generated by Gu.
# 此示例示意bool真值测试函数的重写
class MyList:
    """定义一个容器类,用于存储任意类型的数据
    其内部的存储方式用list实现现"""

    def __init__(self, iterable):
        self.data = [x for x in iterable]

    def __repr__(self):
        return 'MyList(%s)' % self.data

    def __len__(self):
        print("__len__方法被调用")
        return len(self.data)

    def __bool__(self):
        """bool（obj）函数取值，优先取返回值"""
        print("__bool__方法被调用")
        # 定义规则， 所有元素的和为0，则返回FALSE，否则返回TRUE
        return sum(self.data) != 0


myl = MyList([1, -2, 3, -4])
print(myl)
print('bool (myl) =', bool(myl))
if myl:
    print('myl的布尔值为True')
else:
    print('myl的布尔值为False')
