#  Copyright (c) 2022. Generated by Gu.
class MyInteger:
    def __init__(self, value):
        self.data = value

    def __repr__(self):
        return 'MyInteger(%d)' % self.data

    def __abs__(self):
        if self.data < 0:
            return MyInteger(-self.data)
        return MyInteger(self.data)

    def __len__(self):
        """len(x)"规定只能返回整数值"""
        return 100


I1 = MyInteger(-10)
print(I1)
I2 = abs(I1)
print(I2)
print(len(I1))
