#  Copyright (c) 2022. Generated by Gu.
# 此示例示意数值类型转换函数重写
class MyNumber:
    """此类是自定义的类,用于表示自定义数字的类型"""

    def __init__(self, v):
        self.data = v

    def __repr__(self):
        return "MyNumber(%s)" % self.data * 10

    def __int__(self):
        return int(self.data)


n1 = MyNumber('100')
print(n1)
print(int(n1))  # ??????
